@Server_HostAddress = https://localhost:7116

GET {{Server_HostAddress}}/api/AI/extract/?url=https://www.simplyrecipes.com/recipes/beef_wellington/
Accept: application/json

###

GET {{Server_HostAddress}}/api/AI/create/?url=https://www.simplyrecipes.com/recipes/beef_wellington/
Accept: application/json

###

GET {{Server_HostAddress}}/api/recipes
Accept: application/json

###

GET {{Server_HostAddress}}/api/recipes/2
Accept: application/json

###

PUT {{Server_HostAddress}}/api/recipes/2
Accept: application/json